### ISSUE TITLE
Allow interface name and HTTP bind address/port configuration for otbr-web

### ISSUE THREAD

**Issue by farshidtz** [canonical/openthread-border-router-snap#15]
Defaults are:
- interface name: `wpan0` (see https://github.com/canonical/openthread-border-router-snap/issues/17)
- HTTP bind address: `::`
- HTTP bind port: `80`

CLI usage:
```
Usage: otbr-web [-d DEBUG_LEVEL] [-I interfaceName] [-p port] [-a listenAddress] [-v]
```

Source code:
https://github.com/openthread/ot-br-posix/blob/main/src/web/main.cpp

**Comment by wido** [comment]
I would like to have this feature as well. Allows me to have OTBR listen on 8080 and put a reverse SSL proxy in front of it.

**Comment by farshidtz** [comment]
@wido this has been implemented and is now available under the `latest/beta` channel. Please test and report if you find any issues.

```
sudo snap install openthread-border-router --channel=latest/beta
# or simply:
sudo snap install openthread-border-router --beta
```
